
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: test_manager
    ports:
      - 5432:5432
  # app:
  #   build:
  #     context: .
  #   image: test-manager-dev
  #   ports:
  #     - 3000:3000
  #   environment:
  #     NODE_ENV: development  
    # development:
    #   watch:
    #     - action: sync
    #       path: ./src
    #       target: /app/src
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json
